image: Visual Studio 2017

before_build:
  - ps: >-
      $buildId = $env:APPVEYOR_BUILD_NUMBER.PadLeft(5, '0');
      $versionSuffixPR = "-PR$($env:APPVEYOR_PULL_REQUEST_NUMBER)-$buildId";
      $branchName = "$env:APPVEYOR_REPO_BRANCH".Replace("_","");
      $versionSuffixBRANCH = "-$branchName-$buildId";
      $env:VersionSuffix = if ("$env:APPVEYOR_REPO_TAG" -eq "true") { "" } else { if ("$env:APPVEYOR_PULL_REQUEST_NUMBER") { $versionSuffixPR } else { $versionSuffixBRANCH } };

init:
  - git config --global core.autocrlf input
build_script:
  - cmd: echo vs %VersionSuffix%"
  - cmd: build.bat
test_script:
  - cmd: dotnet run --project .\Tests\Tests.fsproj -c Release --framework net461
  - cmd: dotnet run --project .\Tests.FSharpData\Tests.FSharpData.fsproj -c Release --framework net461
  - cmd: dotnet run --project .\Tests.NewtonsoftJson\Tests.NewtonsoftJson.fsproj -c Release --framework net461

artifacts:
  # pushing all *.nupkg files in build directory recursively
  - path: '**\*.nupkg'
    name: nupkgs
    type: NuGetPackage
nuget:
  account_feed: true
  project_feed: true
#  disable_publish_on_pr: false
